# Generated by Django 5.1.3 on 2024-12-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("preview_img", models.ImageField(upload_to="blog/preview_img/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_published", models.BooleanField(default=False)),
                ("count_views", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "пост",
                "verbose_name_plural": "посты",
                "db_table": "posts_table",
                "ordering": ["title"],
            },
        ),
    ]
