# Generated by Django 5.1.3 on 2024-12-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("city", models.CharField(max_length=30)),
                ("phone_number", models.IntegerField(max_length=10)),
            ],
            options={
                "verbose_name": "контакт",
                "verbose_name_plural": "контакты",
                "db_table": "contacts_table",
                "ordering": ["city"],
            },
        ),
    ]
